namespace ETS.Models
{
    public class Member : Person
    {
        public decimal Balance { get; set; }

        public Member(string name, string email, decimal balance)
            : base(name, email)
        {
            Balance = balance;
        }

        public bool Deduct(decimal amount)
        {
            if (Balance < amount) return false;
            Balance -= amount;
            return true;
        }
    }
}
